# Generated by Django 5.2.9 on 2026-02-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('github_link', models.URLField(blank=True, help_text='Link for Technical Score', null=True)),
                ('leetcode_link', models.URLField(blank=True, help_text='Link for Problem Solving Score', null=True)),
                ('linkedin_link', models.URLField(blank=True, help_text='Link for Professional Readiness', null=True)),
                ('portfolio_link', models.URLField(blank=True, help_text='Link for Portfolio/Projects', null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_skills_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('practical_score', models.IntegerField(default=0)),
                ('problem_solving_score', models.IntegerField(default=0)),
                ('professional_score', models.IntegerField(default=0)),
                ('crs_score', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('github_verified', models.BooleanField(default=False)),
                ('leetcode_solved', models.IntegerField(default=0)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='api.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.jobposting'),
        ),
    ]
